name: Replace Header and Remove Duplicate Styles

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  replace-and-clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1️⃣ Replace <header> tags once per file
      - name: Replace <header> with header.html (once per file)
        run: |
          echo "🔄 Replacing <header> with header.html..."
          find . -type f -name "*.html" | while read file; do
            sed -i '0,/<header>/s//header.html/' "$file"
          done
          echo "✅ Replacement complete."

      # 2️⃣ Commit the header replacement
      - name: Commit and push header replacements
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet && echo "No header changes to commit." || (
            git commit -m "🔄 Replace <header> tags with header.html (once per file)"
            git push
          )

      # 3️⃣ Remove duplicate dropdown styles
      - name: Find and Clean ROBUST Duplicate Styles (Flexible Match)
        id: cleanup_step_robust
        run: |
          set -e
          TOTAL_REMOVED=0
          echo "🧹 Starting flexible duplicate cleanup..."

          # Find all .html files recursively
          find . -name "*.html" -type f -print0 | while IFS= read -r -d '' HTML_FILE; do
            perl -0777 -pe '
              BEGIN { our %seen; our $removed = 0; }

              # Capture all <style>...</style> blocks
              s{
                (<style\b[^>]*>.*?</style>)
              }{
                my $block = $1;
                my $norm = $block;
                $norm =~ s/\s+/ /g;   # normalize whitespace

                # Detect dropdown style blocks loosely (both .dropdown and .dropdown-content)
                if ($norm =~ /\.dropdown\s*\{.*?display:\s*inline-block;.*?\}\s*\.dropdown-content/s) {
                  my $sig = "dropdown_signature";
                  if (!$seen{$sig}++) {
                    $block   # keep first one
                  } else {
                    $removed++;
                    ""       # delete duplicates
                  }
                } else {
                  $block     # keep all non-dropdown styles
                }
              }egsx;

              END { print STDERR "::notice ::Removed $removed duplicate dropdown style block(s)\n"; }
            ' "$HTML_FILE" > "$HTML_FILE.tmp"

            if ! cmp -s "$HTML_FILE" "$HTML_FILE.tmp"; then
              mv "$HTML_FILE.tmp" "$HTML_FILE"
              echo "::notice file=${HTML_FILE}::Processed and cleaned."
              TOTAL_REMOVED=1
            else
              rm -f "$HTML_FILE.tmp"
            fi
          done

          echo "total_removed=${TOTAL_REMOVED}" >> "$GITHUB_OUTPUT"
          echo "✅ Cleanup complete."

      # 4️⃣ Commit and push cleanup changes
      - name: Commit and push cleanup
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No cleanup changes to commit."
          else
            git commit -m "🧹 Auto-clean duplicate dropdown styles after header replacement"
            git push
          fi
