name: Remove Duplicate Dropdown Styles

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual run from Actions tab

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and Clean ROBUST Duplicate Styles (Flexible Match)
        id: cleanup_step_robust
        run: |
          set -e
          TOTAL_REMOVED=0
          echo "Starting flexible duplicate cleanup..."

          # Find all .html files recursively
          find . -name "*.html" -type f -print0 | while IFS= read -r -d '' HTML_FILE; do
            perl -0777 -pe '
              BEGIN { our %seen; our $removed = 0; }

              # Capture all <style>...</style> blocks
              s{
                (<style\b[^>]*>.*?</style>)
              }{
                my $block = $1;
                my $norm = $block;
                $norm =~ s/\s+/ /g;   # normalize whitespace

                # Detect dropdown style blocks loosely (both .dropdown and .dropdown-content)
                if ($norm =~ /\.dropdown\s*\{.*?display:\s*inline-block;.*?\}\s*\.dropdown-content/s) {
                  my $sig = "dropdown_signature";
                  if (!$seen{$sig}++) {
                    $block   # keep first one
                  } else {
                    $removed++;
                    ""       # delete duplicates
                  }
                } else {
                  $block     # keep all non-dropdown styles
                }
              }egsx;

              END { print STDERR "::notice ::Removed $removed duplicate dropdown style block(s)\n"; }
            ' "$HTML_FILE" > "$HTML_FILE.tmp"

            if ! cmp -s "$HTML_FILE" "$HTML_FILE.tmp"; then
              mv "$HTML_FILE.tmp" "$HTML_FILE"
              echo "::notice file=${HTML_FILE}::Processed and cleaned."
              TOTAL_REMOVED=1
            else
              rm -f "$HTML_FILE.tmp"
            fi
          done

          echo "total_removed=${TOTAL_REMOVED}" >> "$GITHUB_OUTPUT"

      - name: Commit and push cleanup
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "🧹 Auto-clean duplicate dropdown styles"
            git push
          fi
