name: Global CSS Duplicate Cleanup

# Define when the workflow should run
on:
  push:
    # Only run if any HTML file is pushed
    paths:
      - '**/*.html'
  # Allows you to manually trigger the workflow from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_styles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Find and Clean Duplicate Styles in all HTML Files
      id: cleanup_step
      # We use a multi-line Bash script to loop through files and apply the AWK logic
      run: |
        # 1. Define the unique signature for the style block.
        #    We use 'grep -v' to strip out all white-space (spaces, newlines, tabs) 
        #    from the block definition, making the pattern robust.
        
        # The first few lines of the style block (used as the search pattern):
        STYLE_PATTERN='
        .dropdown {  position: relative;  display: inline-block;}.dropdown-content {
        display: none;  position: absolute;  top: 100%;  right: 0;  left: auto;
        background: #222;  padding: 0.5rem 0;  border-radius: 6px;  box-shadow: 0 4px 8px rgba(0,0,0,0.3);'
        
        # The full, literal, single-line duplicate block used for detection:
        FULL_PATTERN_START='<style>.dropdown {  position: relative;  display: inline-block;}.dropdown-content {  display: none;  position: absolute;  top: 100%;  right: 0;  left: auto;  background: #222;  padding: 0.5rem 0;  border-radius: 6px;  box-shadow: 0 4px 8px rgba(0,0,0,0.3);  min-width: 180px;  z-index: 1000;}.dropdown-content a {  display: block;  padding: 0.5rem 1rem;  color: #ddd;  text-decoration: none;  transition: background 0.3s, color 0.3s;}.dropdown-content a:hover {  background: #333;  color: #ff6600;}.dropdown:hover .dropdown-content {  display: block;}</style>'
        
        # Initialize a counter for tracking overall changes
        TOTAL_REMOVED=0
        
        echo "Searching for the exact duplicate style block pattern in all HTML files..."
        
        # 2. Loop through all HTML files found recursively
        for HTML_FILE in $(find . -name "*.html" -type f); do
          
          # Use grep to count how many times the pattern appears in the file
          COUNT=$(grep -c -F "${FULL_PATTERN_START}" "$HTML_FILE" || true)
          
          # Log what we found
          echo "Processing ${HTML_FILE}: Found ${COUNT} instance(s) of the duplicate style block."
          
          # Check if there are duplicates (i.e., more than 1 instance)
          if [ "$COUNT" -gt 1 ]; then
            
            # --- AWK Execution ---
            # -v sig="${FULL_PATTERN_START}" passes the pattern to AWK
            # $0 ~ sig is the search condition
            # count++ increments the counter every time the pattern is matched
            # if (count > 1) { next } skips printing any instance after the first
            
            awk -v sig="${FULL_PATTERN_START}" '
            $0 ~ sig {
                count++;
                if (count > 1) {
                    next 
                }
            }
            { 
                print 
            }
            ' "$HTML_FILE" > temp.html
            # --- End AWK Execution ---
            
            # 3. Replace the original file with the cleaned temporary file
            mv temp.html "$HTML_FILE"
            
            REMOVED=$((COUNT - 1))
            TOTAL_REMOVED=$((TOTAL_REMOVED + REMOVED))
            
            echo "::notice file=${HTML_FILE}::Removed ${REMOVED} duplicate style tag(s) from ${HTML_FILE}. One copy remains."
          else
            echo "Skipping ${HTML_FILE}: No duplicates found (or only 1 instance present)."
          fi
          
        done
        
        echo "---"
        echo "Summary: Total duplicates removed across all files: ${TOTAL_REMOVED}"
        
        # Set an output variable to use in the next step (Commit)
        echo "total_removed=${TOTAL_REMOVED}" >> "$GITHUB_OUTPUT"

    - name: Commit and Push Changes (If any duplicates were removed)
      # Condition to run this step only if at least one duplicate was removed
      if: steps.cleanup_step.outputs.total_removed > 0
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "CI: Consolidated redundant dropdown styles across all HTML files"
        # Since we modified the files in place, this commits all modified HTML files
        file_pattern: '**/*.html'
