name: Replace All Headers

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  replace-header:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace headers safely (final strict cleanup)
        shell: bash
        run: |
          set -e
          new_header=$(cat header.html)

          echo "🔧 Starting header replacement (strict + safe)..."

          find . -type f -name "*.html" -not -path "./.git/*" | while read -r file; do
            echo ""
            echo "→ Processing $file"

            if grep -q "<header" "$file"; then
              cp "$file" "$file.bak"

              # Count how many dropdown styles exist BEFORE cleanup
              found_count=$(grep -Poz "(?s)<style>.*?\.dropdown.*?</style>" "$file" | grep -c "<style>" || true)
              echo "Found $found_count <style> block(s) containing .dropdown"

              # 1️⃣ Remove all but the first dropdown-style block (handles multi-line safely)
              perl -0777 -i -pe '
                my $first = 0;
                s{
                  (<style>[\s\S]*?\.dropdown[\s\S]*?<\/style>)
                }{
                  if ($first++) { "" } else { $1 }
                }gsex
              ' "$file"

              # 2️⃣ Remove leftover empty <style></style> tags
              perl -0777 -i -pe 's|<style>\s*</style>||gs' "$file"

              # 3️⃣ Replace the header with the one from header.html
              perl -0777 -i -pe "s|<header>.*?</header>|$new_header|gs" "$file"

              # 4️⃣ Clean up blank lines left from removals
              sed -i '/^$/N;/^\n$/D' "$file"

              # Count remaining dropdown styles
              remaining_count=$(grep -Poz "(?s)<style>.*?\.dropdown.*?</style>" "$file" | grep -c "<style>" || true)
              removed=$((found_count - remaining_count))
              if [ "$removed" -lt 0 ]; then removed=0; fi

              echo "Removed $removed duplicate <style> block(s)"
              echo "Remaining $remaining_count unique dropdown <style> block(s)"
              echo "✅ Cleaned successfully"
            else
              echo "⚠️  No <header> found in $file — skipped."
            fi
          done

          echo ""
          echo "✅ Header replacement and cleanup complete (strict mode)."

      - name: Commit and push if changes
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Automated header update via header.html (strict, clean, final)"
            git push
            echo "🚀 Header changes pushed successfully!"
          fi
