name: Replace All Headers

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  replace-header:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace headers safely (guaranteed cleanup for styles)
        shell: bash
        run: |
          set -e
          new_header=$(cat header.html)

          echo "🔧 Starting header replacement (guaranteed strict mode)..."

          find . -type f -name "*.html" -not -path "./.git/*" | while read -r file; do
            echo ""
            echo "→ Processing $file"

            if grep -q "<header" "$file"; then
              cp "$file" "$file.bak"

              # Count how many dropdown style blocks exist before cleanup
              # NOTE: Using a simpler grep for the count to be less fragile
              found_count=$(grep -Poz "(?s)<style[[:space:]]*[^>]*>.*?\.dropdown.*?</style>" "$file" | grep -c "<style>" || true)
              echo "Found $found_count <style> block(s) containing .dropdown"
              
              # --- MODIFIED CLEANUP LOGIC ---
              
              # 1️⃣ REMOVE *ALL* existing dropdown-style blocks from the file
              # This ensures no duplicates are left before inserting the new header.
              # Your new 'header.html' must contain the single correct style block.
              echo "Attempting to remove all existing dropdown style blocks..."
              perl -0777 -i -pe '
                s{
                  <style\b[^>]*>\s*[\s\S]*?\.dropdown[\s\S]*?<\/style>
                }{}gsex
              ' "$file"

              # 2️⃣ Remove leftover empty <style></style> tags completely
              perl -0777 -i -pe 's|<style[^>]*>\s*</style>||g' "$file"

              # 3️⃣ Replace <header> with header.html contents
              perl -0777 -i -pe "s|<header>.*?</header>|$new_header|gs" "$file"

              # 4️⃣ Clean up blank lines left after removals
              sed -i '/^$/N;/^\n$/D' "$file"
              
              # --- END MODIFIED LOGIC ---

              # Count remaining dropdown style blocks (should be 1 if header.html is correct)
              remaining_count=$(grep -Poz "(?s)<style[[:space:]]*[^>]*>.*?\.dropdown.*?</style>" "$file" | grep -c "<style>" || true)
              removed=$((found_count - remaining_count))

              # If the new header had one, and we found 23, removed should be 22.
              # We use a simpler message now since the goal is to remove ALL old ones.
              if [ "$found_count" -gt "0" ]; then 
                echo "Finished style cleanup: All old dropdown style blocks removed."
              fi
              
              echo "Total dropdown style blocks remaining (should be 1 from new header): $remaining_count"
              echo "✅ Cleaned successfully"
            else
              echo "⚠️ No <header> found in $file — skipped."
            fi
          done

          echo ""
          echo "✅ Header replacement and cleanup complete (guaranteed mode)."

      - name: Commit and push if changes
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Automated header update via header.html (strict, guaranteed cleanup)"
            git push
            echo "🚀 Header changes pushed successfully!"
          fi
