name: Replace All Headers

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  replace-header:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace headers safely (no loss of original styles)
        shell: bash
        run: |
          set -e
          new_header=$(cat header.html)

          echo "🔧 Starting header replacement (safe mode)..."

          find . -type f -name "*.html" -not -path "./.git/*" | while read -r file; do
            echo "→ Processing $file"

            if grep -q "<header" "$file"; then
              cp "$file" "$file.bak"

              # 1️⃣ Remove duplicate dropdown-style blocks ONLY (body-level)
              # This targets <style> blocks that define `.dropdown`
              perl -0777 -i -pe '{
                my %seen;
                s{
                  (<style>.*?\.dropdown.*?</style>)
                }{
                  $seen{$1}++ ? "" : $1
                }gsex
              }' "$file"

              # 2️⃣ Replace the header with the one from header.html
              perl -0777 -i -pe "s|<header>.*?</header>|$new_header|gs" "$file"

              # 3️⃣ Optional: Remove excess blank lines after cleanup
              sed -i '/^$/N;/^\n$/D' "$file"
            fi
          done

          echo "✅ Header replacement and cleanup complete (no original styles deleted)."

      - name: Commit and push if changes
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Automated header update via header.html (safe, no duplicate dropdown styles)"
            git push
            echo "🚀 Header changes pushed successfully!"
          fi
