name: Replace Header and Deploy

on:
  push:
    branches: [ main ]   # change if your branch is 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace any header block
        run: |
          find . -type f -name "*.html" -exec perl -0777 -pi -e '
            s|<header>.*?</header>|<header>
  <h1>Lee Family Press</h1>
  <nav>
    <a href="/index.html">Home</a>
    <a href="/works.html">Works</a>
    <a href="#contact">Contact</a>

    <div class="dropdown">
      <a href="#">Authors ▾</a>
      <div class="dropdown-content">
        <a href="/authors/jun-hee-lee.html">Jun Hee Lee</a>
        <a href="/authors/jaewon-lee.html">Jaewon Lee</a>
      </div>
    </div>
  </nav>
</header>

<style>
/* Dropdown wrapper */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Dropdown menu */
.dropdown-content {
  display: none;
  position: absolute;
  top: 100%;
  right: 0;          /* keeps aligned with Authors link */
  left: auto;        /* prevent sticking to page edge */
  background: #222;
  padding: 0.5rem 0;
  border-radius: 6px;
  box-shadow: 0 4px 8px rgba(0,0,0,0.3);
  min-width: 180px;
  z-index: 1000;
}

/* Links inside dropdown */
.dropdown-content a {
  display: block;
  padding: 0.5rem 1rem;
  color: #ddd;
  text-decoration: none;
  transition: background 0.3s, color 0.3s;
}

.dropdown-content a:hover {
  background: #333;
  color: #ff6600;
}

/* Show dropdown on hover */
.dropdown:hover .dropdown-content {
  display: block;
}
</style>|gs' {} +

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
