name: Header Update and Style Cleanup

# Runs when you push code to main/master, or run it manually
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  update-header:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Replace headers and clean styles (FASTER, single-pass)
        run: |
          # Set Git user/email
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # 1. Load header.html content into a variable quickly
          # This line removes newlines and escapes quotes for safe injection.
          NEW_HEADER_CONTENT=$(cat header.html | tr '\n' ' ' | tr "'" '"')

          # 2. Process ALL HTML files in ONE single, fast Perl command
          # This is the key to preventing the timeout.
          perl -0777 -pi -e '
            # A. Remove ALL repeated style blocks with .dropdown
            s|<style\b[^>]*>\s*\.dropdown\b.*?<\/style>||gis;

            # B. Remove ALL old <header>...</header> blocks
            s|<header\b[^>]*>.*?</header>||gis;

            # C. Insert the NEW header content after the <body> tag
            if (s|(<body[^>]*>)|$1\n'"$NEW_HEADER_CONTENT"'|i) {} 
          ' $(find . -type f -name "*.html" ! -name "header.html")

          # 3. Commit changes once
          git add "*.html"
          git commit -m "Automated: Cleaned redundant styles and updated headers." || echo "No changes to commit"
          git push
